apiVersion: apps/v1
kind: Deployment
metadata:
  name: financeappbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financeappbackend
  template:
    metadata:
      labels:
        app: financeappbackend
    spec:
   
      containers:
      - name: financeapp
        image: aksfinance.azurecr.io/backend:latest
        # volumeMounts:
        #   - name: volume112
        #     mountPath: "/mnt/secrets-store"
        #     readOnly: true

      # volumes:
      #   - name: volume112
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: "sqlsecretclass"  

      #   volumeMounts:
      # - name: secrecy
      #   mountPath: "/mnt/secrets-store"
      #   readOnly: true
        
        env:
        - name: SQL_CONNECTION
          valueFrom:
            secretKeyRef:
              name: SQL_CONNECTION   # the name of your Secret
              key: SQL_CONNECTION_KEY          # the key inside the Secret

      # volumes:
      #   - name: secrecy
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: "sqlsecretclass"

---
apiVersion: v1
kind: Service 
metadata:
  name: financeappbackend-svc
spec:
  # type: LoadBalancer
  selector:
    app: financeappbackend
  ports: 
    - name: http
      port: 80
      targetPort: 3000
