apiVersion: apps/v1
kind: Deployment
metadata:
  name: financeappbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financeappbackend
  template:
    metadata:
      labels:
        app: financeappbackend
        azure.workload.identity/use: "true"
    spec:
      # serviceAccountName: workload-identity-sa2
      nodeSelector:
        agentpool: agentpool  # <-- This targets the specific node pool
      containers:
      - name: financeapp
        image: aksfinance.azurecr.io/backend:latest
        env:
        - name: SQL_CONNECTION_STRING
          value: Server=tcp:sql112.database.windows.net;Database=sqldb1;Encrypt=True;TrustServerCertificate=False;Authentication=ActiveDirectoryDefault;
          # value: Server=tcp:sql112.database.windows.net,1433;Initial Catalog=sqldb1;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication="Active Directory Default";
       


---
apiVersion: v1
kind: Service 
metadata:
  name: financeappbackend-svc
spec:
  # type: LoadBalancer
  selector:
    app: financeappbackend
  ports: 
    - name: http
      port: 80
      targetPort: 3000
