apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sqlsecretclass
  namespace: backend
  annotations:
    secrets-store.csi.k8s.io/rotation-poll-interval: "2m"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 8468252f-1e36-437b-9be5-c9e731e7f8a5
    keyvaultName: dolcegabbana
    cloudName: ""
    objects: |
      array:
        - |
          objectName: sql-connection
          objectType: secret
          objectVersion: ""
    tenantId: 17a09c66-f406-4897-8b24-51f5313623dc

  secretObjects:
    - secretName: sql-connection #creates k8s secret with this name
      type: Opaque
      data:
        - key: sql_connection_key #this is the key in k8s secret
          objectName: sql-connection # this is the reference to secret provider class which fetches kv
