# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sqlsecretclass
spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: <client-id>   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: dolcegabbana     # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQL_CONNECTION
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    
    tenantId: 17a09c66-f406-4897-8b24-51f5313623dc             # The tenant ID of the key vault

  # secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  # - data:
  #   - key: SQL_CONNECTION_KEY                           # name of key getting creating in aks secret
  #     objectName: SQL_CONNECTION                      # name of keyvault secret
  #   secretName: SQL_CONNECTION                     # name of the Kubernetes secret object
  #   type: Opaque   