apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sqlsecretclass
  namespace: backend
  annotations:
    secrets-store.csi.k8s.io/rotation-poll-interval: "2m"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 2dd055a2-46b4-445a-ad98-f890e6edca03
    keyvaultName: dolcegabbana
    cloudName: ""
    objects: |
      array:
        - |
          objectName: sql-connection
          objectType: secret
          objectVersion: ""
    tenantId: 17a09c66-f406-4897-8b24-51f5313623dc

  secretObjects:
    - secretName: sql-connection
      type: Opaque
      data:
        - key: sql_connection_key
          objectName: sql-connection
